### ISSUE TITLE
Does not work with node v9.6.1

### ISSUE THREAD

**Issue by thiemok** [bitchcraft/unicorn-logger#1]
### Expected behaviour
Logger logs to console

### Actual behaviour
No output is printed

### Steps to reproduce
Run this failing test case: `DEBUG=* node index.js`
**index.js**
```js
var UnicornLogger = require('./dist/unicorn-logger.es5');
var logger = new UnicornLogger('test');

logger('direct call');
logger.log('log no group');
logger.warn('warn no group');
logger.error('error no group');
logger.group('group')
	.log('log')
	.warn('warn')
	.error('error')
	.groupEnd();
```

### ENV
node v9.6.1
macOS 10.13.3

**Comment by thiemok** [comment]
Apparently the webpack build defaults to debug not being correctly initialized. Setting `logger.debug.enabled = true;` will result in output being printed, albeit without colors

**Comment by maddrag0n** [comment]
yes, webpack actually strips those process.env checks. need to figure out a way to keep them in there\
