### ISSUE TITLE
plugin architecture

### ISSUE THREAD

**Issue by maddrag0n** [bitchcraft/unicorn-logger#8]
# UnicornLogger Plugin Architecture

**Work in progress**

https://github.com/bitchcraft/unicorn-logger/wiki/Plugin-Architecture

**Comment by thiemok** [comment]
Should we maybe add a namespace param to the middleware interface of `call`? Middlewares and their registered functions are currently not namespace aware.

**Comment by maddrag0n** [comment]
namespace should be a property of `this`, should it not?

**Comment by thiemok** [comment]
This would not work with static middlewares.

**Comment by maddrag0n** [comment]
ofc when they process a message they can check for this.namespace

**Comment by maddrag0n** [comment]
in that case we should add this binding to call

**Comment by maddrag0n** [comment]
or pass the logger

**Comment by thiemok** [comment]
see 35eed6f77ab4809edbaae8ebab95437a0ad2c7c3

**Comment by zGrav** [comment]
Closing #8
